<?php

return [
    ['id' => 1, 'name' => 'Electronics', 'parent_id' => null, 'sort_order' => 1],
    ['id' => 2, 'name' => 'Cell Phones and Tablets', 'parent_id' => 1, 'sort_order' => 1],
    ['id' => 3, 'name' => 'Smartphones', 'parent_id' => 2, 'sort_order' => 1],
    ['id' => 4, 'name' => 'Tablets', 'parent_id' => 2, 'sort_order' => 2],
    ['id' => 5, 'name' => 'Cell Phone Accessories', 'parent_id' => 2, 'sort_order' => 3],
    ['id' => 6, 'name' => 'Cases', 'parent_id' => 5, 'sort_order' => 1],
    ['id' => 7, 'name' => 'Chargers', 'parent_id' => 5, 'sort_order' => 2],
    ['id' => 8, 'name' => 'Computers and IT', 'parent_id' => 1, 'sort_order' => 2],
    ['id' => 9, 'name' => 'Notebooks', 'parent_id' => 8, 'sort_order' => 1],
    ['id' => 10, 'name' => 'Desktops', 'parent_id' => 8, 'sort_order' => 2],
    ['id' => 11, 'name' => 'Computer Accessories', 'parent_id' => 8, 'sort_order' => 3],
    ['id' => 12, 'name' => 'Keyboards', 'parent_id' => 11, 'sort_order' => 1],
    ['id' => 13, 'name' => 'Mice', 'parent_id' => 11, 'sort_order' => 2],
    ['id' => 14, 'name' => 'Audio and Video', 'parent_id' => 1, 'sort_order' => 3],
    ['id' => 15, 'name' => 'TVs', 'parent_id' => 14, 'sort_order' => 1],
    ['id' => 16, 'name' => 'Home Theaters', 'parent_id' => 14, 'sort_order' => 2],
    ['id' => 17, 'name' => 'Headphones', 'parent_id' => 14, 'sort_order' => 3],
    ['id' => 18, 'name' => 'Bluetooth', 'parent_id' => 17, 'sort_order' => 1],
    ['id' => 19, 'name' => 'Wired', 'parent_id' => 17, 'sort_order' => 2],
    ['id' => 20, 'name' => 'Fashion', 'parent_id' => null, 'sort_order' => 2],
    ['id' => 21, 'name' => 'Clothing', 'parent_id' => 20, 'sort_order' => 1],
    ['id' => 22, 'name' => 'Men', 'parent_id' => 21, 'sort_order' => 1],
    ['id' => 23, 'name' => 'Shirts', 'parent_id' => 22, 'sort_order' => 1],
    ['id' => 24, 'name' => 'Pants', 'parent_id' => 22, 'sort_order' => 2],
    ['id' => 25, 'name' => 'Women', 'parent_id' => 21, 'sort_order' => 2],
    ['id' => 26, 'name' => 'Dresses', 'parent_id' => 25, 'sort_order' => 1],
    ['id' => 27, 'name' => 'Skirts', 'parent_id' => 25, 'sort_order' => 2],
    ['id' => 28, 'name' => 'Kids', 'parent_id' => 21, 'sort_order' => 3],
    ['id' => 29, 'name' => 'Boys', 'parent_id' => 28, 'sort_order' => 1],
    ['id' => 30, 'name' => 'Girls', 'parent_id' => 28, 'sort_order' => 2],
    ['id' => 31, 'name' => 'Footwear', 'parent_id' => 20, 'sort_order' => 2],
    ['id' => 32, 'name' => 'Men\'s', 'parent_id' => 31, 'sort_order' => 1],
    ['id' => 33, 'name' => 'Women\'s', 'parent_id' => 31, 'sort_order' => 2],
    ['id' => 34, 'name' => 'Sports', 'parent_id' => 31, 'sort_order' => 3],
    ['id' => 35, 'name' => 'Sneakers', 'parent_id' => 34, 'sort_order' => 1],
    ['id' => 36, 'name' => 'Soccer Shoes', 'parent_id' => 34, 'sort_order' => 2],
    ['id' => 37, 'name' => 'Accessories', 'parent_id' => 20, 'sort_order' => 3],
    ['id' => 38, 'name' => 'Bags', 'parent_id' => 37, 'sort_order' => 1],
    ['id' => 39, 'name' => 'Watches', 'parent_id' => 37, 'sort_order' => 2],
    ['id' => 40, 'name' => 'Jewelry', 'parent_id' => 37, 'sort_order' => 3],
    ['id' => 41, 'name' => 'Home and Garden', 'parent_id' => null, 'sort_order' => 3],
    ['id' => 42, 'name' => 'Furniture', 'parent_id' => 41, 'sort_order' => 1],
    ['id' => 43, 'name' => 'Living Room', 'parent_id' => 42, 'sort_order' => 1],
    ['id' => 44, 'name' => 'Sofas', 'parent_id' => 43, 'sort_order' => 1],
    ['id' => 45, 'name' => 'Coffee Tables', 'parent_id' => 43, 'sort_order' => 2],
    ['id' => 46, 'name' => 'Bedroom', 'parent_id' => 42, 'sort_order' => 2],
    ['id' => 47, 'name' => 'Beds', 'parent_id' => 46, 'sort_order' => 1],
    ['id' => 48, 'name' => 'Wardrobes', 'parent_id' => 46, 'sort_order' => 2],
    ['id' => 49, 'name' => 'Kitchen', 'parent_id' => 42, 'sort_order' => 3],
    ['id' => 50, 'name' => 'Tables', 'parent_id' => 49, 'sort_order' => 1],
    ['id' => 51, 'name' => 'Chairs', 'parent_id' => 49, 'sort_order' => 2],
    ['id' => 52, 'name' => 'Decoration', 'parent_id' => 41, 'sort_order' => 2],
    ['id' => 53, 'name' => 'Paintings', 'parent_id' => 52, 'sort_order' => 1],
    ['id' => 54, 'name' => 'Vases', 'parent_id' => 52, 'sort_order' => 2],
    ['id' => 55, 'name' => 'Lighting', 'parent_id' => 52, 'sort_order' => 3],
    ['id' => 56, 'name' => 'Chandeliers', 'parent_id' => 55, 'sort_order' => 1],
    ['id' => 57, 'name' => 'Lamps', 'parent_id' => 55, 'sort_order' => 2],
    ['id' => 58, 'name' => 'Gardening', 'parent_id' => 41, 'sort_order' => 3],
    ['id' => 59, 'name' => 'Tools', 'parent_id' => 58, 'sort_order' => 1],
    ['id' => 60, 'name' => 'Plants', 'parent_id' => 58, 'sort_order' => 2],
    ['id' => 61, 'name' => 'Irrigation', 'parent_id' => 58, 'sort_order' => 3],
    ['id' => 62, 'name' => 'Sports and Leisure', 'parent_id' => null, 'sort_order' => 4],
    ['id' => 63, 'name' => 'Fitness', 'parent_id' => 62, 'sort_order' => 1],
    ['id' => 64, 'name' => 'Gym Equipment', 'parent_id' => 63, 'sort_order' => 1],
    ['id' => 65, 'name' => 'Treadmills', 'parent_id' => 64, 'sort_order' => 1],
    ['id' => 66, 'name' => 'Exercise Bikes', 'parent_id' => 64, 'sort_order' => 2],
    ['id' => 67, 'name' => 'Supplements', 'parent_id' => 63, 'sort_order' => 2],
    ['id' => 68, 'name' => 'Proteins', 'parent_id' => 67, 'sort_order' => 1],
    ['id' => 69, 'name' => 'Vitamins', 'parent_id' => 67, 'sort_order' => 2],
    ['id' => 70, 'name' => 'Sportswear', 'parent_id' => 63, 'sort_order' => 3],
    ['id' => 71, 'name' => 'Men\'s', 'parent_id' => 70, 'sort_order' => 1],
    ['id' => 72, 'name' => 'Women\'s', 'parent_id' => 70, 'sort_order' => 2],
    ['id' => 73, 'name' => 'Outdoor Sports', 'parent_id' => 62, 'sort_order' => 2],
    ['id' => 74, 'name' => 'Camping', 'parent_id' => 73, 'sort_order' => 1],
    ['id' => 75, 'name' => 'Tents', 'parent_id' => 74, 'sort_order' => 1],
    ['id' => 76, 'name' => 'Backpacks', 'parent_id' => 74, 'sort_order' => 2],
    ['id' => 77, 'name' => 'Cycling', 'parent_id' => 73, 'sort_order' => 2],
    ['id' => 78, 'name' => 'Bicycles', 'parent_id' => 77, 'sort_order' => 1],
    ['id' => 79, 'name' => 'Cycling Accessories', 'parent_id' => 77, 'sort_order' => 2],
    ['id' => 80, 'name' => 'Fishing', 'parent_id' => 73, 'sort_order' => 3],
    ['id' => 81, 'name' => 'Fishing Rods', 'parent_id' => 80, 'sort_order' => 1],
    ['id' => 82, 'name' => 'Baits', 'parent_id' => 80, 'sort_order' => 2],
    ['id' => 83, 'name' => 'Toys and Games', 'parent_id' => 62, 'sort_order' => 3],
    ['id' => 84, 'name' => 'Educational Toys', 'parent_id' => 83, 'sort_order' => 1],
    ['id' => 85, 'name' => 'Board Games', 'parent_id' => 83, 'sort_order' => 2],
    ['id' => 86, 'name' => 'Electronic Toys', 'parent_id' => 83, 'sort_order' => 3],
];